{% set name = "starry" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 955799a486afc8ec7337c272d41bbd5f327f6465abc73c049eb1d6d3f577a509

build:
  number: 2
  skip: True  # [win]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - pybind11
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - matplotlib-base
    - pillow

test:
  imports:
    - starry
    - starry.maps

about:
  home: http://github.com/rodluger/starry
  license: GPL-3.0
  license_family: GPL
  license_file: LICENSE
  summary: 'Analytic occultation light curves for astronomy'
  description: |
    The starry code package enables the computation of light curves for various
    applications in astronomy including transits and secondary eclipses of
    exoplanets, light curves of eclipsing binaries, rotational phase curves of
    exoplanets, light curves of planet-planet and planet-moon occultations, and
    more.
  doc_url: https://rodluger.github.io/starry/
  dev_url: https://github.com/rodluger/starry

extra:
  recipe-maintainers:
    - dfm
    - rodluger
