appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: AmVsDwZYnrXUmlBHkH/hcG6P1p1FWQ9qpoO3r5x3cOmq3rEYiRuU4RQ6PugsgumSYdd5XlQ3T1kJE6fnY952WwdEh2zTMepUvVKZKhvgTFtt6ehMX4hBWyFCmA+pOzYDThDKo9vio5E155ekptXKdtaMZxBfKJSO1w6qH9RzKlhe51rRxkFQwnvUJU4Wmm+4hVssDCoRgm/lqXBXiOGj9eH2ak80dUhbPbg9VbbrwwqYIDMSPFV2Cgi4HeQsp8k3C8NS65nEjfHyibcAb67FLuWUlEYOUuqSI1UpXfTAm5WmSY5TrfqdFp93aRmCbxmj2CA/JFJJAafzFB3rBjraatx0VtCZth76uLs6rzTVwz32Au+K2/C1p/MWqKmoLkiA8G1GqSr7V9I8zdNxAHxC8J1dq1lLC/nh+lrySQLoqg5gLpWDhHInSDL6mlV7UPyxTvvKQJd78Bwj0Uh0BSfSz+Ea6/J9s7PHae1CFT78Nd8CGjFTdMsg9DJiV91iC3wEMiHZLKb/QJm8NCV0ELkjO5VM1B0iYGrnAfDWFRPPnNhWl3SkUmmnfeTHmi7qXnqSuhr5re0kflVjg4bDVccpAKcrUQi8t1UY2J97yU/h3kf5TRQMjazX854FNx9e4yXbxFDTrbdiBF0nfoW19jsv+w5o1DPBVUA7EPRK1EfW+G8=}
conda_forge_output_validation: true
