travis:
  secure:
    BINSTAR_TOKEN: cR0bRcTeHf/VS/wRlZI89ESK4hZppHefPzFxExj1iPNhLtMlsaoNiOE+/AAEGfq70Vq0E32BxHznbmP3FczY1w4WtGjTZlbf/F7ZcvskfkMuTOJTYcRaMt8n2E13CvCziM5/G8NlDeZzMET1Reg/+E0wZs1gQTjhgeV/4ClCKsVfYj3bHrX8QWT3Hqx+cXY/Mt/h7UUuKG3i9WzIoL+ABYyNfLd+8SSFXXPKjL6KqNEpiz6zTK5CpLwVUU/O5Sgsm2079moWjDN0aVSVS1XvJV+xZDM0l3C6fcufWZfGJTyf3voZFA3QOST5PBNEYNfzqaKE7lKA/bsEomJKeW/nOB92pvwNAWn+2/KQIZxRza6XMn/Jx4WgmxnSNPWq9AhFrFtRuLZxM2Sq6B/sUPj0SAbk89v/iOv54/EBrv9jh6bKSdyWlr7SnzUMzNkhfOIfZ+Mw/ldmscze9YYg024EzhLKc6baywKTSHz2NQ2Eo+7XZw186TPn5HS7VlL8tNcXxbJyzqleJVWdTIcZ3PyHmLVg3GtD05YjfXP26UMSYypNVSDJmvT0M1BYa9icOXXAgCmZreNc0h6W9FkV/RgLejhLLLsnwPs0WqKkNxYyMshc1z/qVRUPTw7QCfz2KfVRVBM1DAOwliR8JRjZNBfxg+PRNs15P387EPKkDpHshsk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
